# database.py

PEPTIDE_PRESETS = {
    "AOD-9604": {
        "vial_mg": 5.0, "dose_mcg": 300.0, "default_dose_unit": "mcg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Fat Loss", "filter_cat": "Slimming & Fat Loss",
        "desc": "Anti-Obesity Drug 9604. A modified fragment of the C-terminus of Human Growth Hormone (HGH).",
        "benefits_summary": "- Targeted fat burning (lipolysis)\n- No blood sugar spikes\n- Cartilage repair support\n- Non-hormonal (no IGF-1 impact)",
        "side_effects_summary": "- Injection site redness\n- Mild stomach upset (rare)\n- Headache (rare)",
        "protocol_summary": "300mcg daily, morning fasted.",
        "benefits_detailed": "- **Targeted Lipolysis:** Specifically stimulates the breakdown of fat cells.\n- **Metabolic Safety:** Does not induce insulin resistance.\n- **Joint Support:** Aids in cartilage regeneration.",
        "protocol_detailed": "**Dosage:** 300mcg (0.3mg)\n**Frequency:** Daily\n**Timing:** Morning (Fasted)\n**Cycle:** 3 to 6 Months",
        "side_effects_detailed": "• Extremely well tolerated\n• Minor injection site reactions\n• Mild headache (rare)",
        "storage": "Refrigerate. Stable."
    },
    "BPC-157": {
        "vial_mg": 5.0, "dose_mcg": 250.0, "default_dose_unit": "mcg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Regenerative", "filter_cat": "Injury & Repair",
        "desc": "Body Protection Compound-157. A 15-amino acid chain derived from gastric juice.",
        "benefits_summary": "- Accelerates tendon/ligament repair\n- Heals gut lining\n- Reduces neuro-inflammation",
        "side_effects_summary": "- Mild nausea (rare)\n- Injection site irritation",
        "protocol_summary": "250-500mcg daily or 2x daily.",
        "benefits_detailed": "- **Connective Tissue:** Speeds up soft tissue healing.\n- **Angiogenesis:** New blood vessel formation.\n- **Gastroprotection:** Heals gastric ulcers.",
        "protocol_detailed": "**Dosage:** 250mcg - 500mcg\n**Frequency:** Daily or Twice Daily\n**Timing:** SubQ near injury or belly fat\n**Cycle:** 4-6 Weeks on, 2 off",
        "side_effects_detailed": "• Generally very safe\n• Rare reports of fatigue\n• Mild nausea",
        "storage": "Refrigerate after mixing."
    },
    "BPC-157 + TB-500 Blend": {
        "vial_mg": 10.0, "dose_mcg": 500.0, "default_dose_unit": "mcg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Regenerative Blend", "filter_cat": "Injury & Repair",
        "desc": "The 'Wolverine Stack'. Synergistic combination of BPC-157 and TB-500.",
        "benefits_summary": "- Maximum surgical/injury recovery\n- Improves joint flexibility\n- Systemic anti-inflammatory",
        "side_effects_summary": "- Head rush (TB-500)\n- Fatigue/Lethargy",
        "protocol_summary": "500mcg-1mg total fluid daily.",
        "benefits_detailed": "- **Total Repair:** Targets tendon and muscle simultaneously.\n- **Mobility:** Improves range of motion.",
        "protocol_detailed": "**Dosage:** 500mcg - 1000mcg\n**Frequency:** Daily\n**Cycle:** 4 to 8 Weeks",
        "side_effects_detailed": "• Temporary head rush\n• Fatigue (body repairing)\n• Injection site stinging",
        "storage": "Refrigerate. Use within 30 days."
    },
    "CJC-1295 (No DAC)": {
        "vial_mg": 5.0, "dose_mcg": 100.0, "default_dose_unit": "mcg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Growth Hormone", "filter_cat": "Muscle & Workout",
        "desc": "Modified GRF 1-29. Stimulates pulsatile Growth Hormone release.",
        "benefits_summary": "- Lean muscle mass\n- Deep slow-wave sleep\n- Skin elasticity",
        "side_effects_summary": "- Flushing/Warmth\n- Head rush\n- Vivid dreams",
        "protocol_summary": "100mcg nightly, fasted.",
        "benefits_detailed": "- **Hyperplasia:** Stimulates muscle cell division.\n- **Sleep:** Improves Stage 4 deep sleep.",
        "protocol_detailed": "**Dosage:** 100mcg\n**Frequency:** 5 days on / 2 off\n**Timing:** Bedtime (Fasted 2+ hours)",
        "side_effects_detailed": "• Immediate head rush\n• Warm/flushed face\n• Vivid dreams",
        "storage": "Refrigerate. Sensitive to light."
    },
    "CJC-1295 + Ipamorelin Blend": {
        "vial_mg": 10.0, "dose_mcg": 200.0, "default_dose_unit": "mcg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Growth Hormone Blend", "filter_cat": "Muscle & Workout",
        "desc": "The Gold Standard GH Stack.",
        "benefits_summary": "- Max natural GH secretion\n- Body recomposition\n- Superior recovery",
        "side_effects_summary": "- Head rush/Flushing\n- Numb fingers\n- Water retention",
        "protocol_summary": "200-300mcg total nightly, fasted.",
        "benefits_detailed": "- **Synergy:** Maximizes GH naturally.\n- **Visceral Fat:** Mobilizes deep abdominal stores.",
        "protocol_detailed": "**Dosage:** 200mcg - 300mcg\n**Frequency:** 5 days on / 2 off\n**Timing:** Bedtime",
        "side_effects_detailed": "• Flushing\n• Numbness in hands\n• Initial water weight",
        "storage": "Refrigerate. Do not shake."
    },
    "Epithalon": {
        "vial_mg": 10.0, "dose_mcg": 5000.0, "default_dose_unit": "mcg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Anti-Aging", "filter_cat": "Wellness & Longevity",
        "desc": "Synthetic tetrapeptide that increases telomerase activity.",
        "benefits_summary": "- Extends lifespan (Telomeres)\n- Resets circadian rhythm\n- Boosts melatonin",
        "side_effects_summary": "- Daytime drowsiness (rare)\n- Vivid dreams",
        "protocol_summary": "5mg-10mg daily for 10-20 days.",
        "benefits_detailed": "- **Telomere Extension:** Protects DNA.\n- **Endocrine Reset:** Restores hypothalamus sensitivity.",
        "protocol_detailed": "**Dosage:** 5mg - 10mg\n**Cycle:** 10-20 Day Course (Repeat every 6-12 months)",
        "side_effects_detailed": "• Extremely safe\n• Vivid dreams",
        "storage": "Refrigerate."
    },
    "GHK-Cu": {
        "vial_mg": 50.0, "dose_mcg": 2000.0, "default_dose_unit": "mg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Cosmetic/Repair", "filter_cat": "Skin, Hair & Beauty",
        "desc": "Copper Tripeptide-1. Resets over 4,000 genes.",
        "benefits_summary": "- Boosts collagen & elastin\n- Tightens skin\n- Regrows hair",
        "side_effects_summary": "- Painful injection (Sting)\n- Red welts\n- Zinc depletion",
        "protocol_summary": "1-2mg daily. Evening.",
        "benefits_detailed": "- **Skin:** Increases collagen synthesis by 70%.\n- **Hair:** Enlarges follicles.",
        "protocol_detailed": "**Dosage:** 1mg - 2mg\n**Timing:** Evening (rotate sites)\n**Cycle:** 30 Days on/off",
        "side_effects_detailed": "• High incidence of pain\n• Red welts\n• Supplement Zinc (50mg)",
        "storage": "Refrigerate."
    },
    "Glow Blend (GHK-Cu/BPC/TB)": {
        "vial_mg": 70.0, "dose_mcg": 2500.0, "default_dose_unit": "mg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Cosmetic/Recovery Blend", "filter_cat": "Skin, Hair & Beauty",
        "desc": "70mg Tri-Blend. BPC-157 buffers GHK-Cu sting.",
        "benefits_summary": "- Painless GHK-Cu injection\n- Total skin tightening\n- Rapid recovery",
        "side_effects_summary": "- Mild redness\n- Flushing\n- Fatigue",
        "protocol_summary": "2.5mg - 3mg total daily.",
        "benefits_detailed": "- **Painless:** BPC-157 neutralizes acidity.\n- **Total Rejuvenation:** Skin, hair, and gut.",
        "protocol_detailed": "**Dosage:** 2.5mg - 3mg\n**Timing:** Evening\n**Cycle:** 4-6 Weeks",
        "side_effects_detailed": "• Mild redness\n• Temporary flushing",
        "storage": "Refrigerate."
    },
    "HCG": {
        "vial_mg": 5000.0, "dose_mcg": 250.0, "default_dose_unit": "IU", "default_stock_unit": "IU", "iu_conversion": 1,
        "type": "Hormonal", "filter_cat": "Libido & Sexual Health",
        "desc": "Human Chorionic Gonadotropin. Mimics LH.",
        "benefits_summary": "- Prevents testicular shrinkage\n- Maintains fertility\n- Boosts libido",
        "side_effects_summary": "- Estrogen spikes\n- Acne\n- Water retention",
        "protocol_summary": "250-500 IU 2-3x per week.",
        "benefits_detailed": "- **Testicular Health:** Prevents atrophy during TRT.\n- **Fertility:** Maintains sperm production.",
        "protocol_detailed": "**Dosage:** 250 IU - 500 IU\n**Frequency:** 2 to 3 times per week",
        "side_effects_detailed": "• Estrogen spikes\n• Acne\n• Gynecomastia risk",
        "storage": "Refrigerate. Fragile."
    },
    "Ipamorelin": {
        "vial_mg": 5.0, "dose_mcg": 100.0, "default_dose_unit": "mcg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Growth Hormone", "filter_cat": "Muscle & Workout",
        "desc": "Selective GH Secretagogue. Mildest and safest GHRP.",
        "benefits_summary": "- Clean GH release (No hunger)\n- Fat loss\n- Improved sleep",
        "side_effects_summary": "- Very mild\n- Slight water retention",
        "protocol_summary": "100-300mcg nightly, fasted.",
        "benefits_detailed": "- **Pure Signal:** No hunger spikes.\n- **Sleep:** Increases REM and Slow-Wave stages.",
        "protocol_detailed": "**Dosage:** 100mcg - 300mcg\n**Timing:** Before Bed",
        "side_effects_detailed": "• Well tolerated\n• No 'jittery' feeling",
        "storage": "Refrigerate."
    },
    "Kisspeptin": {
        "vial_mg": 10.0, "dose_mcg": 100.0, "default_dose_unit": "mcg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Hormonal", "filter_cat": "Libido & Sexual Health",
        "desc": "Stimulates hypothalamus to release GnRH.",
        "benefits_summary": "- Restarts HPTA axis safely\n- Boosts fertility\n- Increases libido",
        "side_effects_summary": "- Flushing/Warmth\n- Injection site redness",
        "protocol_summary": "100-200mcg daily.",
        "benefits_detailed": "- **HPTA Restart:** Safe natural testosterone restart.\n- **Fertility:** Stimulates FSH.",
        "protocol_detailed": "**Dosage:** 100mcg - 200mcg\n**Cycle:** 4 Weeks (PCT)",
        "side_effects_detailed": "• Mild flushing\n• Headache",
        "storage": "Refrigerate."
    },
    "Klow Blend (GHK-Cu/BPC/TB/KPV)": {
        "vial_mg": 80.0, "dose_mcg": 3000.0, "default_dose_unit": "mg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Ultimate Repair/Cosmetic Blend", "filter_cat": "Skin, Hair & Beauty",
        "desc": "80mg Master Stack. Adds KPV for dermatology.",
        "benefits_summary": "- Clears Acne, Psoriasis, Eczema\n- Heals Gut (IBD)\n- Systemic anti-inflammatory",
        "side_effects_summary": "- Red welts\n- Fatigue\n- Flushing",
        "protocol_summary": "3mg total daily.",
        "benefits_detailed": "- **Dermatology:** KPV treats inflammatory skin conditions.\n- **Gut Health:** Strongest stack for IBD.",
        "protocol_detailed": "**Dosage:** 3mg\n**Timing:** Evening\n**Cycle:** 4-8 Weeks",
        "side_effects_detailed": "• Red welts (common)\n• Healing fatigue",
        "storage": "Refrigerate."
    },
    "Melanotan II": {
        "vial_mg": 10.0, "dose_mcg": 500.0, "default_dose_unit": "mcg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Cosmetic", "filter_cat": "Skin, Hair & Beauty",
        "desc": "Alpha-MSH analog. Tanning and arousal.",
        "benefits_summary": "- Deep, rapid tan\n- Extreme libido boost\n- Appetite suppression",
        "side_effects_summary": "- Severe Nausea\n- Spontaneous erections\n- Darkening moles",
        "protocol_summary": "100-500mcg before UV exposure.",
        "benefits_detailed": "- **Photoprotection:** Natural UV defense.\n- **Libido:** Potent aphrodisiac.",
        "protocol_detailed": "**Dosage:** 100mcg - 500mcg\n**Timing:** 30 mins before UV",
        "side_effects_detailed": "• Nausea (1-2 hours)\n• Darkening of freckles",
        "storage": "Refrigerate."
    },
    "MOTS-c": {
        "vial_mg": 10.0, "dose_mcg": 5000.0, "default_dose_unit": "mg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Metabolic/Mitochondrial", "filter_cat": "Muscle & Workout",
        "desc": "Mitochondrial-Derived 'exercise mimetic'.",
        "benefits_summary": "- Increases VO2 Max\n- Prevents weight gain\n- Cellular energy boost",
        "side_effects_summary": "- Painful injection\n- Insomnia\n- Hyperactivity",
        "protocol_summary": "5mg once weekly.",
        "benefits_detailed": "- **Endurance:** Increases glucose utilization.\n- **Biogenesis:** New mitochondria creation.",
        "protocol_detailed": "**Dosage:** 5mg - 10mg\n**Frequency:** Once Weekly\n**Timing:** Morning",
        "side_effects_detailed": "• Injection pain (common)\n• Restlessness",
        "storage": "Refrigerate."
    },
    "NAD+": {
        "vial_mg": 500.0, "dose_mcg": 25000.0, "default_dose_unit": "mg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Cellular Energy", "filter_cat": "Wellness & Longevity",
        "desc": "Nicotinamide Adenine Dinucleotide. Fuel for cells.",
        "benefits_summary": "- Clears brain fog\n- Repairs DNA damage\n- Anti-aging",
        "side_effects_summary": "- Chest pressure (The Flush)\n- Anxiety/Panic feeling\n- Nausea",
        "protocol_summary": "25-50mg 2-3x per week. SLOW.",
        "benefits_detailed": "- **Cognition:** Enhances mental sharpness.\n- **Mitochondria:** Restores ATP production.",
        "protocol_detailed": "**Dosage:** 25mg - 50mg\n**Note:** INJECT SLOWLY to avoid flush.",
        "side_effects_detailed": "• Intense chest pressure\n• Abdominal cramping",
        "storage": "Refrigerate immediately."
    },
    "Oxytocin Acetate": {
        "vial_mg": 2.0, "dose_mcg": 20.0, "default_dose_unit": "IU", "default_stock_unit": "mg", "iu_conversion": 600,
        "type": "Hormonal/Wellness", "filter_cat": "Nootropics & Brain",
        "desc": "The 'Love Hormone'. Social bonding and anxiety reduction.",
        "benefits_summary": "- Reduces social anxiety\n- Lowers cortisol\n- Enhances bonding",
        "side_effects_summary": "- Nausea\n- Headache\n- Flushing",
        "protocol_summary": "20-50 IU as needed.",
        "benefits_detailed": "- **Psychological:** Reduces stress levels.\n- **Intimacy:** Enhances trust.",
        "protocol_detailed": "**Dosage:** 10 IU - 25 IU\n**Timing:** 30 mins before social events",
        "side_effects_detailed": "• Nausea at high doses\n• Dizziness",
        "storage": "Refrigerate."
    },
    "PT-141": {
        "vial_mg": 10.0, "dose_mcg": 1000.0, "default_dose_unit": "mg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Libido", "filter_cat": "Libido & Sexual Health",
        "desc": "Bremelanotide. Targets the nervous system for arousal.",
        "benefits_summary": "- Treats ED & Low Libido\n- Works when Viagra fails\n- Increases physical arousal",
        "side_effects_summary": "- Nausea (Common)\n- Flushing\n- Headache",
        "protocol_summary": "1.5-2mg, 2 hours before activity.",
        "benefits_detailed": "- **Mechanism:** Targets the hypothalamus.\n- **Response:** Increases physical desire.",
        "protocol_detailed": "**Dosage:** 1.5mg - 2mg\n**Timing:** 2-4 hours BEFORE activity",
        "side_effects_detailed": "• Nausea (40% of users)\n• Elevated blood pressure",
        "storage": "Refrigerate."
    },
    "Retatrutide": {
        "vial_mg": 10.0, "dose_mcg": 2000.0, "default_dose_unit": "mg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Metabolic (GLP-1/GIP/Glucagon)", "filter_cat": "Slimming & Fat Loss",
        "desc": "The 'Triple G' Agonist. Most potent weight loss agent.",
        "benefits_summary": "- Extreme weight loss (24%)\n- Burns liver fat\n- Increases metabolism",
        "side_effects_summary": "- High Heart Rate\n- Skin sensitivity\n- Nausea",
        "protocol_summary": "2mg weekly, titrate up.",
        "benefits_detailed": "- **Efficacy:** 24.2% average weight loss.\n- **Liver:** Resolves Fatty Liver (NAFLD).",
        "protocol_detailed": "**Dosage:** Start 2mg -> Max 12mg\n**Frequency:** Once Weekly",
        "side_effects_detailed": "• Tachycardia\n• Sensitive skin",
        "storage": "Refrigerate."
    },
    "Semaglutide": {
        "vial_mg": 5.0, "dose_mcg": 250.0, "default_dose_unit": "mg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Metabolic (GLP-1)", "filter_cat": "Slimming & Fat Loss",
        "desc": "GLP-1 Agonist. Standard for medical weight loss.",
        "benefits_summary": "- Significant weight loss (15%)\n- Controls blood sugar\n- Reduces addiction cravings",
        "side_effects_summary": "- Nausea/Vomiting\n- Constipation\n- Fatigue",
        "protocol_summary": "0.25mg weekly, titrate up.",
        "benefits_detailed": "- **Satiety:** Slows gastric emptying.\n- **Heart:** 20% reduction in cardiac events.",
        "protocol_detailed": "**Dosage:** Start 0.25mg -> Max 2.4mg\n**Frequency:** Once Weekly",
        "side_effects_detailed": "• Nausea/Vomiting\n• 'Ozempic face'",
        "storage": "Refrigerate."
    },
    "TB-500": {
        "vial_mg": 5.0, "dose_mcg": 2500.0, "default_dose_unit": "mg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Regenerative", "filter_cat": "Injury & Repair",
        "desc": "Synthetic Thymosin Beta-4. Muscle and tissue repair.",
        "benefits_summary": "- Heals muscle tears\n- Improves flexibility\n- Reduces scar tissue",
        "side_effects_summary": "- Head rush\n- Lethargy\n- Flu-like symptoms",
        "protocol_summary": "2.5mg twice weekly.",
        "benefits_detailed": "- **Muscle Repair:** Primary peptide for strains.\n- **Flexibility:** Reduces inflammation.",
        "protocol_detailed": "**Dosage:** 2.5mg (2500mcg)\n**Frequency:** 2x Per Week",
        "side_effects_detailed": "• Temporary head rush\n• Occasional lethargy",
        "storage": "Refrigerate."
    },
    "Tesamorelin": {
        "vial_mg": 2.0, "dose_mcg": 1000.0, "default_dose_unit": "mg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Growth Hormone", "filter_cat": "Slimming & Fat Loss",
        "desc": "FDA Approved GHRH for visceral fat.",
        "benefits_summary": "- Burns belly fat\n- Increases muscle tone\n- Nootropic effects",
        "side_effects_summary": "- Injection redness\n- Joint stiffness\n- Carpal Tunnel",
        "protocol_summary": "1-2mg nightly, fasted.",
        "benefits_detailed": "- **Visceral Fat:** Targets stubborn organ fat.\n- **Cognition:** Improves executive function.",
        "protocol_detailed": "**Dosage:** 1mg - 2mg\n**Timing:** Before Bed (Fasted)",
        "side_effects_detailed": "• Joint stiffness\n• Carpal tunnel numbness",
        "storage": "Refrigerate."
    },
    "Tesamorelin + Ipamorelin Blend": {
        "vial_mg": 12.0, "dose_mcg": 350.0, "default_dose_unit": "mcg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Growth Hormone/Fat Loss Blend", "filter_cat": "Slimming & Fat Loss",
        "desc": "The 'Shred Stack'.",
        "benefits_summary": "- Max fat loss (Visceral)\n- Muscle definition\n- Deep sleep",
        "side_effects_summary": "- Flushing/Redness\n- Joint stiffness",
        "protocol_summary": "350-500mcg total nightly, fasted.",
        "benefits_detailed": "- **Recomposition:** Powerful fat burning combo.\n- **Synergy:** Better sleep and recovery.",
        "protocol_detailed": "**Dosage:** 350mcg - 500mcg\n**Frequency:** Daily (5 on / 2 off)",
        "side_effects_detailed": "• Joint pain\n• Water retention",
        "storage": "Refrigerate."
    },
    "Tirzepatide": {
        "vial_mg": 30.0, "dose_mcg": 2.5, "default_dose_unit": "mg", "default_stock_unit": "mg", "iu_conversion": None,
        "type": "Metabolic (GLP-1/GIP)", "filter_cat": "Slimming & Fat Loss",
        "desc": "Dual Agonist (Mounjaro). GIP + GLP-1.",
        "benefits_summary": "- Massive weight loss (22%)\n- Eliminates 'Food Noise'\n- Metabolic repair",
        "side_effects_summary": "- Anhedonia (No joy)\n- Constipation\n- Hair shedding",
        "protocol_summary": "2.5mg weekly, titrate up.",
        "benefits_detailed": "- **Weight Loss:** Superior to Semaglutide.\n- **Food Noise:** Stops obsessive food thoughts.",
        "protocol_detailed": "**Dosage:** Start 2.5mg -> Max 15mg\n**Frequency:** Once Weekly",
        "side_effects_detailed": "• Anhedonia (flat mood)\n• Cold extremities",
        "storage": "Refrigerate."
    },
}
